version: '2'

services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      examplenw:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
      - "5778"
      - "14268"
    ports:
      - "9411:9411"
      - "16686:16686"
      - "5778:5778"
      - "14268:14268"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
  prometheus:
    image: prom/prometheus
    networks:
      examplenw:
        aliases:
          - prometheus
    expose:
      - "9090"
    ports:
      - "9090:9090"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    networks:
      examplenw:
        aliases:
          - rabbitmq
    expose:
      - "15672"
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  kafka:
    image:  spotify/kafka
    hostname: "kafka"
    networks:
      examplenw:
        aliases:
          - kafka
    expose:
      - "2181"
      - "9092"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=0.0.0.0
      - ADVERTISED_PORT=9092

networks:
  examplenw: {}