name: E2E
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Starting dependencies
        run:  |
          docker-compose up -d
        working-directory: ./examples/

      - name: Starting service
        run:  |
          go build . 
          nohup ./service &
        working-directory: ./examples/service

      - name: Starting client
        run:  |
          sleep 10
          go run main.go
        working-directory: ./examples/client
