name: E2E
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'      

      - name: Starting dependencies
        run:  |
          docker-compose up -d
          sleep 10
        working-directory: ./examples/

      - name: Starting service
        run:  |
          docker ps -a
          go build . 
          nohup ./service &
        working-directory: ./examples/service

      - name: Starting client
        run:  |
          sleep 10
          go run main.go
        working-directory: ./examples/client
