name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint and fmt check
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Linting and fmt check
        run: make lint

  build:
    name: CI on Go ${{ matrix.go-image-version}}
    strategy:
      matrix:
        go-image-version: ["1.21"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go-image-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-image-version }}

      - name: Check out source code
        uses: actions/checkout@v4

      - name: Start dependencies
        run: make deps-start

      - name: Wait dependencies
        run: sleep 60

      - name: Running CI
        run: make ci

      - name: Convert coverage file to lcov
        run: |
          GO111MODULE=off go get -u github.com/jandelgado/gcov2lcov
          $(go env GOPATH)/bin/gcov2lcov -infile=coverage.txt -outfile=coverage.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
